# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scope.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1706, 727)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1330, 500, 291, 81))
        self.pushButton.setObjectName("pushButton")
        self.Estop = QtWidgets.QPushButton(self.centralwidget)
        self.Estop.setCheckable(True)
        self.Estop.setGeometry(QtCore.QRect(1330, 500, 291, 81))
        self.Estop.setObjectName("Estop")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 10, 299, 338))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.CHANnel3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CHANnel3.setObjectName("CHANnel3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.CHANnel3)
        self.CHANnel4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CHANnel4.setObjectName("CHANnel4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.CHANnel4)
        self.All = QtWidgets.QCheckBox(self.layoutWidget)
        self.All.setObjectName("All")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.All)
        self.CHANnel2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CHANnel2.setObjectName("CHANnel2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.CHANnel2)
        self.CHANnel1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.CHANnel1.setObjectName("CHANnel1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.CHANnel1)
        self.same = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.same.setFont(font)
        self.same.setObjectName("same")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.same)
        self.MATH = QtWidgets.QCheckBox(self.layoutWidget)
        self.MATH.setObjectName("MATH")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.MATH)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(810, 10, 167, 97))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.layoutWidget_2)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.AC = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.AC.setObjectName("AC")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.AC)
        self.DC = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.DC.setObjectName("DC")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.DC)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 120, 219, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 400, 1261, 261))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(1010, 10, 551, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.layoutWidget3)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_5.addWidget(self.textBrowser_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(370, 10, 168, 130))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.NORMal = QtWidgets.QRadioButton(self.layoutWidget4)
        self.NORMal.setObjectName("NORMal")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.NORMal)
        self.MAXimum = QtWidgets.QRadioButton(self.layoutWidget4)
        self.MAXimum.setObjectName("MAXimum")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.MAXimum)
        self.RAW = QtWidgets.QRadioButton(self.layoutWidget4)
        self.RAW.setObjectName("RAW")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.RAW)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(540, 10, 263, 69))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.trigger = QtWidgets.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.trigger.setFont(font)
        self.trigger.setObjectName("trigger")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.trigger)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(540, 90, 165, 95))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.layoutWidget6)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.POSitive = QtWidgets.QRadioButton(self.layoutWidget6)
        self.POSitive.setObjectName("POSitive")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.POSitive)
        self.NEGative = QtWidgets.QRadioButton(self.layoutWidget6)
        self.NEGative.setObjectName("NEGative")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.NEGative)
        self.layoutWidget7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 10, 184, 95))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.layoutWidget7)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.STOP = QtWidgets.QRadioButton(self.layoutWidget7)
        self.STOP.setObjectName("STOP")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.STOP)
        self.TD = QtWidgets.QRadioButton(self.layoutWidget7)
        self.TD.setObjectName("TD")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.TD)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1706, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menu_Tools = QtWidgets.QMenu(self.menubar)
        self.menu_Tools.setObjectName("menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnection = QtWidgets.QAction(MainWindow)
        self.actionConnection.setObjectName("actionConnection")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionScope_Settings = QtWidgets.QAction(MainWindow)
        self.actionScope_Settings.setObjectName("actionScope_Settings")
        self.action_WaveForm_Viewer = QtWidgets.QAction(MainWindow)
        self.action_WaveForm_Viewer.setObjectName("action_WaveForm_Viewer")
        self.action_Counter = QtWidgets.QAction(MainWindow)
        self.action_Counter.setObjectName("action_Counter")
        self.menuFile.addAction(self.actionConnection)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addSeparator()
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionScope_Settings)
        self.menu_Tools.addAction(self.action_WaveForm_Viewer)
        self.menu_Tools.addAction(self.action_Counter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.All.pressed.connect(self.CHANnel1.click)
        self.All.pressed.connect(self.CHANnel2.click)
        self.All.pressed.connect(self.CHANnel3.click)
        self.All.pressed.connect(self.CHANnel4.click)
        self.trigger.pressed.connect(self.POSitive.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.CHANnel1, self.CHANnel2)
        MainWindow.setTabOrder(self.CHANnel2, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.CHANnel4)
        MainWindow.setTabOrder(self.CHANnel4, self.CHANnel3)
        MainWindow.setTabOrder(self.CHANnel3, self.All)
        MainWindow.setTabOrder(self.All, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.textBrowser_2)
        MainWindow.setTabOrder(self.textBrowser_2,self.Estop)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rigol DS1000z Scope WaveForm Saver"))
        self.pushButton.setText(_translate("MainWindow", "Save Waveforms"))
        self.Estop.setText(_translate("MainWindow", "Stop !"))
        self.label_2.setText(_translate("MainWindow", " Sources"))
        self.CHANnel3.setText(_translate("MainWindow", "Channel 3"))
        self.CHANnel4.setText(_translate("MainWindow", "Channel 4"))
        self.All.setText(_translate("MainWindow", "   All"))
        self.CHANnel2.setText(_translate("MainWindow", "Channel 2"))
        self.CHANnel1.setText(_translate("MainWindow", "Channel 1"))
        self.same.setText(_translate("MainWindow", "Coincidentally"))
        self.MATH.setText(_translate("MainWindow", "MATH"))
        self.label_5.setText(_translate("MainWindow", "Trigger Coupling"))
        self.AC.setText(_translate("MainWindow", "AC"))
        self.DC.setText(_translate("MainWindow", "DC"))
        self.label.setText(_translate("MainWindow", "Number of WaveForms"))
        self.label_4.setText(_translate("MainWindow", "Status:"))
        self.pushButton_3.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "File Destination"))
        self.label_7.setText(_translate("MainWindow", "WaveForm Mode"))
        self.NORMal.setText(_translate("MainWindow", "Normal"))
        self.MAXimum.setText(_translate("MainWindow", "Maximum"))
        self.RAW.setText(_translate("MainWindow", "Raw"))
        self.trigger.setText(_translate("MainWindow", "Trigger Control"))
        self.label_6.setText(_translate("MainWindow", "Set Trigger"))
        self.label_8.setText(_translate("MainWindow", "Trigger Edges"))
        self.POSitive.setText(_translate("MainWindow", "Positive Edge"))
        self.NEGative.setText(_translate("MainWindow", "Negative Edge"))
        self.STOP.setText(_translate("MainWindow", "On STOP"))
        self.TD.setText(_translate("MainWindow", "On TRIGGER"))
        self.label_9.setText(_translate("MainWindow", "Capture "))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools"))
        self.actionConnection.setText(_translate("MainWindow", "&Connection"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionScope_Settings.setText(_translate("MainWindow", "&Scope Settings"))
        self.action_WaveForm_Viewer.setText(_translate("MainWindow", "&WaveForm Viewer"))
        self.action_Counter.setText(_translate("MainWindow", "&Counter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

